# Generated by Django 5.0 on 2023-12-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='value',
            field=models.CharField(default='ceaser', max_length=10),
        ),
    ]
